# Generated by Django 5.2.4 on 2025-08-28 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('objectives', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('input_content', models.TextField(help_text='The base content or brief for generation.')),
                ('linkedin_content', models.TextField(blank=True, null=True)),
                ('x_content', models.TextField(blank=True, null=True, verbose_name='X (Twitter) Content')),
                ('facebook_content', models.TextField(blank=True, null=True)),
                ('instagram_content', models.TextField(blank=True, null=True)),
                ('youtube_content', models.TextField(blank=True, null=True, verbose_name='YouTube Description/Script')),
                ('quora_content', models.TextField(blank=True, null=True)),
                ('reddit_content', models.TextField(blank=True, null=True)),
                ('blog_content', models.TextField(blank=True, null=True)),
                ('image_prompt', models.TextField(blank=True, null=True)),
                ('video_prompt', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaign_images/%Y/%m/%d/')),
                ('video', models.FileField(blank=True, null=True, upload_to='campaign_videos/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campaigns.campaign')),
            ],
        ),
    ]
